### ISSUE TITLE
Unable to install from the Foundry VTT Module Installation List

### ISSUE THREAD

**Issue by kuentzel** [RedReign/FoundryVTT-BetterRolls5e#29]
Method 2 (pasting the link to module.json) works.
Method 1 does not, prompting the following error:

Installation failed: invalid json response body at [the link to module.json]:
Unexpected token : in JSON at position 3

**Comment by Jonwh25** [comment]
foundry.js:23852 FetchError: invalid json response body at https://raw.githubusercontent.com/RedReign/FoundryVTT-BetterRolls5e/1.0.6(FVTT-0.6.0)/betterrolls5e/module.json reason: Unexpected token : in JSON at position 3
    at /foundryvtt/resources/app/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async checkPackage (/foundryvtt/resources/app/dist/packages/views.js:1:2779)
    at async Object.installPackage (/foundryvtt/resources/app/dist/packages/views.js:1:3625)
    at async setupPost (/foundryvtt/resources/app/dist/views.js:1:6986)

**Comment by RedReign** [comment]
Fixed! Sorry about this issue.
