### ISSUE TITLE
Incompatibility with Foundry VTT  V9.269 dnd5e V1.6.2

### ISSUE THREAD

**Issue by jmurrayufo** [RedReign/FoundryVTT-BetterRolls5e#383]
helpers.mjs:428 Uncaught (in promise) Error: The provided data is not an object!
[Detected 1 package: betterrolls5e]
    at isObjectEmpty (helpers.mjs:428:11)
    at CustomItemRoll.roll (custom-roll.js:705:16)
    at async CustomItemRoll.toMessage (custom-roll.js:824:4)

Rolling an archer with a bow gives a pop up, but clicking the roll results in the following.

**Comment by arbella** [comment]
Me too, any ranged weapon is now broken for me, have to not use this module for the time been.

**Comment by IrmatDen** [comment]
Hi, I have the same issue on Foundry 9.249 using BetterRolls 1.7.2

**Comment by Fenlander216** [comment]
Same here we can't use this mod anymore for rolling in DnD 5th ed.

**Comment by Cubius** [comment]
Further investigation shows that this might only be an issue with ranged weapons/attacks that consume ammunition.
